trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.28
    endpoint: SkillsFundingAgency

pool:
  name: DAS - Continuous Integration Agents
  demands: LATEST_DOTNET_VERSION -equals 3.1

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml