jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - name: BuildConfiguration
    value: release
  - group: BUILD Management Resources
  workspace:
      clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-reservations-jobs
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function App Course'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Functions.RefreshCourse/SFA.DAS.Reservations.Functions.RefreshCourse.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function App Reservation'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Functions.Reservations/SFA.DAS.Reservations.Functions.Reservations.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function App LegalEntities'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Functions.LegalEntities/SFA.DAS.Reservations.Functions.LegalEntities.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
    
  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function App ReservationIndex'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Functions.ReservationIndex/SFA.DAS.Reservations.Functions.ReservationIndex.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish - dotnet publish Function App ProviderPermissions'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Functions.ProviderPermission/SFA.DAS.Reservations.Functions.ProviderPermission.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact - ReservationJobs'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
      artifactName: ${{ parameters.SolutionBaseName }}